export const UPDATE_USERNAME_AND_PASSWORD = "UPDATE_USERNAME_AND_PASSWORD";
export const UPDATE_SESSION_TOKEN_ETC = "UPDATE_SESSION_TOKEN_ETC";
export const UPDATE_HISTORY = "UPDATE_HISTORY";
export const UPDATE_EVERYTHING = "UPDATE_EVERYTHING";